name: taskist
description: Task List App

version: 0.9.2+4

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: any
  firebase_auth: ^0.8.0+3
  # firebase_messaging: ^2.0.1
  #  firebase_remote_config: ^0.0.6+1
  firebase_analytics: any
  firebase_storage: any
  image:
  cloud_firestore: 0.9.0
  strings:
  uuid:
  # fast_qr_reader_view:
  location:
  camera:
  carousel_slider:
  cloud_functions:
  firestore_helpers:
  jaguar_serializer:

  scoped_model:
  font_awesome_flutter: ^8.0.1
  flutter_colorpicker: ^0.0.7
  flutter_slidable: ^0.4.5
  url_launcher: ^3.0.3
  image_picker:
  dio:
  share: ^0.5.3
  latlong:
  flutter_map:
  datetime_picker_formfield:
  unicorndial: ^1.1.5
  flutter_background_geolocation:
  launch_review: ^1.0.1
  modal_progress_hud: ^0.1.0
  connectivity: ^0.3.1
  cupertino_icons: ^0.1.2
  flutter_form_builder:
  barcode_scan: "0.0.8"
  # json_annotation: ^1.0.0
  cached_network_image:
  # googleapis: any
  # googleapis_auth: any
  card_settings:
  zoomable_image:
dev_dependencies:
  build_runner: ^0.10.1
  jaguar_serializer_cli: 2.2.2
  firebase_storage_image:
  firebase_ml_vision:
  rxdart:
  flutter_test:
    sdk: flutter
  cache_image: "^0.0.1"
  # build_runner: ^1.0.0
  # json_serializable: ^1.0.0
  # firebase_admob: ^0.6.1
  # firebase_analytics: ^1.0.3
  # firebase_auth: ^0.5.20
  # firebase_database: ^1.0.4
  # firebase_messaging: 2.1.0
  # cloud_firestore: ^0.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/avatars/
